version: '3.8'

services:
  postgres:
    image: postgres:alpine  # Corrected tag to 'alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 024Wisdom@29

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5556:5556"
    depends_on:
      - postgres
